/* AURA — landing page copy dictionary (EN default + FR) */
AuraI18n.init({
  en: {
    nav_how: "How it works", nav_analyzer: "Analyzer", nav_loyalty: "Loyalty",
    nav_pricing: "Pricing", nav_signin: "Sign in", nav_cta: "Analyze my Instagram",

    hero_badge: "The superfan economy, revealed",
    hero_primary: "Analyze my Instagram", hero_secondary: "See how it works",
    hero_note: "Free audit · No password · Public data only",
    hero_sub: "AURA reads your Instagram audience, estimates your monetization potential, and helps you launch fan passes, VIP access, digital rewards, drops and tokenized loyalty — without the crypto complexity.",
    heroA_title: "Turn your audience into a <span class='hl'>superfan economy.</span>",
    heroB_kicker: "From followers to superfans",
    heroB_title: "Attention is not revenue.<br>Yet.",
    heroB_sub: "Most creators sit on a goldmine they can't see. AURA reveals the value hidden inside your community — and hands you the system to activate it.",
    heroC_title: "Reveal the hidden value of your Instagram community.",
    heroC_sub: "Enter a username. In seconds, see the Superfan Score, monetization potential and the loyalty program your audience is ready for.",
    heroC_ph: "your.username", heroC_btn: "Reveal my score",
    heroC_hint: "Try a public account — e.g. a creator you follow",

    mock_handle: "@maya.studio", mock_meta: "142K followers · Lifestyle & design",
    mock_superfan: "Superfan Score", mock_readiness: "Token readiness",
    mock_revenue: "Est. monthly revenue", mock_potential: "Superfan potential",
    mock_ready_tag: "Ready to launch",

    trust_line: "Built for creators, managers, labels & agencies",
    hero_proof: "Join <b class='hl'>1,250+</b> creators building their superfan economy",
    stat_superfan: "Superfan Score", stat_token: "Token Readiness", stat_revenue: "Revenue Potential", stat_conv: "Conversion Scenario",
    stat_foot_period: "last 30 days", hero_figure: "Figure",
    sig_1: "Followers", sig_2: "Likes", sig_3: "Comments", sig_4: "Shares", sig_5: "Saves", sig_6: "DMs",

    prob_eyebrow: "The problem",
    prob_title: "Your followers are not your community — yet.",
    prob_lede: "You have attention. But attention doesn't automatically become income. Most creators don't know which followers are real superfans, what their community could generate, or what kind of paid experience to launch.",
    prob1_t: "Vanity metrics hide value",
    prob1_d: "Likes and reach look good on a screen but say nothing about who would actually pay to be closer to you.",
    prob2_t: "Platforms own your reach",
    prob2_d: "An algorithm decides who sees you. You rent your audience — you don't own the relationship.",
    prob3_t: "Superfans stay invisible",
    prob3_d: "The 3% who'd buy everything you launch are buried in your followers until something activates them.",

    an_eyebrow: "The hook · Free audit",
    an_title: "Start with your Superfan Score.",
    an_lede: "Drop in any public Instagram handle. AURA turns posts, likes and comments into business signals — in seconds.",
    an_m1: "Engagement rate", an_m2: "Avg. likes", an_m3: "Avg. comments", an_m4: "Post quality",
    an_m5: "Superfan potential", an_m6: "Token readiness", an_m7: "Est. monthly revenue", an_m8: "Best content",
    an_rec_t: "Recommended path",
    an_rec_d: "Launch a Fan Pass at $19 to your top 4% — projected $9.1K in the first 30 days.",
    an_run: "Run a sample analysis",

    tr_eyebrow: "The journey",
    tr_title: "From audience data to a monetization engine.",
    tr_lede: "Five steps. One owned community.",
    tr_s1_t: "Analyze your Instagram", tr_s1_d: "Public data in, business signals out. No password required.",
    tr_s2_t: "Reveal superfan potential", tr_s2_d: "See who's ready to pay and how much your community is worth.",
    tr_s3_t: "Design rewards & VIP access", tr_s3_d: "Configure tiers, perks, badges and unlock conditions visually.",
    tr_s4_t: "Launch your Fan Pass", tr_s4_d: "Ship a tokenized loyalty program — scarcity and status, built in.",
    tr_s5_t: "Track & grow", tr_s5_d: "Follow engagement, retention and revenue from one dashboard.",

    tk_eyebrow: "Invisible infrastructure",
    tk_title: "Tokenization, without the crypto complexity.",
    tk_lede: "Your fans never see a wallet, a chart or a coin. They see passes, badges and access. The token layer quietly powers ownership, scarcity, portability and status in the background.",
    tk_fans: "What your fans get", tk_you: "What powers it",
    tk_f1: "Fan Pass", tk_f2: "VIP Badge", tk_f3: "Reward points", tk_f4: "Private drops",
    tk_f5: "Event access", tk_f6: "Exclusive content", tk_f7: "Community status", tk_f8: "Superfan airdrops",
    tk_p1: "Ownership", tk_p2: "Scarcity", tk_p3: "Portability", tk_p4: "Transparency",
    tk_disclaimer: "AURA currently simulates a future tokenized loyalty layer. It is not connected to a live blockchain and tokens are not investments.",

    db_eyebrow: "The product",
    db_title: "Built for creators who want action, not vanity metrics.",
    db_lede: "Every number ties to a decision: who to reward, what to launch, and how much it could make.",
    db_k1: "Superfan Score", db_k2: "Token readiness", db_k3: "Est. monthly revenue",
    db_k4: "Active pass holders", db_k5: "Reward claims", db_k6: "Community growth",
    db_mod_rev: "Revenue scenarios", db_mod_funnel: "Superfan funnel",
    db_open: "Open the live dashboard",
    db_funnel_1: "Followers", db_funnel_2: "Engaged", db_funnel_3: "Superfans", db_funnel_4: "Pass holders",

    uc_eyebrow: "Possibilities", uc_title: "What can creators launch?",
    uc_lede: "One audience. A dozen ways to turn loyalty into a relationship worth paying for.",
    uc_1: "VIP fan club", uc_2: "Paid private community", uc_3: "Early merch access",
    uc_4: "Backstage access", uc_5: "Exclusive content", uc_6: "Priority event list",
    uc_7: "Digital collectibles", uc_8: "Fan challenges", uc_9: "Reward campaigns",
    uc_10: "Token-gated drops", uc_11: "Loyalty points", uc_12: "Superfan leaderboard",

    pf_eyebrow: "The math · Examples",
    pf_title: "Your next 100 superfans are worth more than 100,000 followers.",
    pf_lede: "Illustrative scenarios — not customer results. Numbers shown are simulations of what an activated community can generate.",
    pf_sim_tag: "Simulation",
    pf_c1_l: "100 superfans", pf_c1_v: "$900", pf_c1_d: "/mo at $9/month membership",
    pf_c2_l: "500 fan passes", pf_c2_v: "$9,500", pf_c2_d: "launch revenue at $19 each",
    pf_c3_l: "Top 4% activated", pf_c3_v: "12×", pf_c3_d: "revenue per fan vs. sponsorships",
    pf_quote: "“I had 140K followers and no idea 4,000 of them would happily pay to be in the room. AURA showed me the room was already there.”",
    pf_quote_by: "Sample creator profile · illustrative",

    pr_eyebrow: "Pricing", pr_title: "Start free. Activate when you're ready.",
    pr_lede: "The audit is always free. Pay only when you launch.",
    pr_monthly: "Monthly", pr_yearly: "Yearly · save 20%", pr_per: "/mo",
    pr_free_n: "Free Audit", pr_free_p: "$0", pr_free_d: "Reveal your potential.",
    pr_launch_n: "Launch", pr_launch_p: "$29", pr_launch_d: "A full plan to go live.",
    pr_pro_n: "Creator Pro", pr_pro_p: "$79", pr_pro_d: "The full monetization engine.",
    pr_agency_n: "Agency / Label", pr_agency_p: "Custom", pr_agency_d: "Many creators, one cockpit.",
    pr_popular: "Most popular",
    pr_cta_free: "Run free audit", pr_cta_paid: "Choose plan", pr_cta_agency: "Talk to us",
    pr_fee_note: "Transaction fees may apply on fan pass sales, tokenized rewards or paid community launches.",
    pr_f_free: "Instagram analysis|Superfan Score|Engagement rate|Token readiness preview|Basic revenue scenario|3 recommendations",
    pr_f_launch: "Everything in Free|Full community diagnostic|Revenue scenarios|Fan Pass strategy|Reward & VIP tier ideas|Launch script|Campaign checklist",
    pr_f_pro: "Everything in Launch|Creator dashboard|Loyalty program builder|Fan pass configuration|Airdrop simulation|Campaign analytics|Exportable launch assets",
    pr_f_agency: "Everything in Pro|Multiple creators|Portfolio dashboard|Creator scoring|Campaign management|Revenue reporting",

    fcta_title: "Your next 100 superfans are already following you.",
    fcta_sub: "Run a free audit and meet the community you didn't know you owned.",
    fcta_btn: "Find them now",

    ft_tag: "Reveal. Connect. Reward.",
    ft_product: "Product", ft_company: "Company", ft_legal: "Legal",
    ft_disclaimer: "AURA is a creator monetization platform. The tokenized loyalty layer is currently a simulation of future infrastructure and is not financial advice or an investment product.",
    ft_rights: "© 2026 AURA. All rights reserved."
  },

  fr: {
    nav_how: "Comment ça marche", nav_analyzer: "Analyseur", nav_loyalty: "Fidélité",
    nav_pricing: "Tarifs", nav_signin: "Se connecter", nav_cta: "Analyser mon Instagram",

    hero_badge: "L'économie des superfans, révélée",
    hero_primary: "Analyser mon Instagram", hero_secondary: "Voir comment ça marche",
    hero_note: "Audit gratuit · Sans mot de passe · Données publiques uniquement",
    hero_sub: "AURA lit votre audience Instagram, estime votre potentiel de monétisation et vous aide à lancer fan passes, accès VIP, récompenses numériques, drops et fidélité tokenisée — sans la complexité de la crypto.",
    heroA_title: "Transformez votre audience en <span class='hl'>économie de superfans.</span>",
    heroB_kicker: "Des followers aux superfans",
    heroB_title: "L'attention n'est pas un revenu.<br>Pas encore.",
    heroB_sub: "La plupart des créateurs sont assis sur une mine d'or qu'ils ne voient pas. AURA révèle la valeur cachée dans votre communauté — et vous donne le système pour l'activer.",
    heroC_title: "Révélez la valeur cachée de votre communauté Instagram.",
    heroC_sub: "Entrez un nom d'utilisateur. En quelques secondes, découvrez le Superfan Score, le potentiel de monétisation et le programme de fidélité pour lequel votre audience est prête.",
    heroC_ph: "votre.pseudo", heroC_btn: "Révéler mon score",
    heroC_hint: "Essayez un compte public — ex. un créateur que vous suivez",

    mock_handle: "@maya.studio", mock_meta: "142K abonnés · Lifestyle & design",
    mock_superfan: "Superfan Score", mock_readiness: "Maturité token",
    mock_revenue: "Revenu mensuel est.", mock_potential: "Potentiel superfan",
    mock_ready_tag: "Prêt à lancer",

    trust_line: "Conçu pour les créateurs, managers, labels & agences",
    hero_proof: "Rejoignez <b class='hl'>1 250+</b> créateurs qui bâtissent leur économie de superfans",
    stat_superfan: "Superfan Score", stat_token: "Maturité token", stat_revenue: "Revenu potentiel", stat_conv: "Scénario de conversion",
    stat_foot_period: "30 derniers jours", hero_figure: "Figure",
    sig_1: "Followers", sig_2: "Likes", sig_3: "Commentaires", sig_4: "Partages", sig_5: "Enregistrements", sig_6: "DMs",

    prob_eyebrow: "Le problème",
    prob_title: "Vos followers ne sont pas encore votre communauté.",
    prob_lede: "Vous avez l'attention. Mais l'attention ne devient pas automatiquement un revenu. La plupart des créateurs ignorent quels followers sont de vrais superfans, ce que leur communauté pourrait générer, ou quelle expérience payante lancer.",
    prob1_t: "Les vanity metrics cachent la valeur",
    prob1_d: "Les likes et la portée font joli à l'écran mais ne disent rien sur qui paierait vraiment pour être plus proche de vous.",
    prob2_t: "Les plateformes possèdent votre portée",
    prob2_d: "Un algorithme décide qui vous voit. Vous louez votre audience — vous ne possédez pas la relation.",
    prob3_t: "Les superfans restent invisibles",
    prob3_d: "Les 3 % qui achèteraient tout ce que vous lancez sont enfouis dans vos followers, jusqu'à ce que quelque chose les active.",

    an_eyebrow: "L'accroche · Audit gratuit",
    an_title: "Commencez par votre Superfan Score.",
    an_lede: "Saisissez n'importe quel compte Instagram public. AURA transforme posts, likes et commentaires en signaux business — en quelques secondes.",
    an_m1: "Taux d'engagement", an_m2: "Likes moy.", an_m3: "Commentaires moy.", an_m4: "Qualité des posts",
    an_m5: "Potentiel superfan", an_m6: "Maturité token", an_m7: "Revenu mensuel est.", an_m8: "Meilleur contenu",
    an_rec_t: "Parcours recommandé",
    an_rec_d: "Lancez un Fan Pass à 19 $ pour vos 4 % les plus actifs — projection de 9,1 K$ sur les 30 premiers jours.",
    an_run: "Lancer une analyse d'exemple",

    tr_eyebrow: "Le parcours",
    tr_title: "Des données d'audience à un moteur de monétisation.",
    tr_lede: "Cinq étapes. Une communauté qui vous appartient.",
    tr_s1_t: "Analysez votre Instagram", tr_s1_d: "Données publiques en entrée, signaux business en sortie. Sans mot de passe.",
    tr_s2_t: "Révélez le potentiel superfan", tr_s2_d: "Voyez qui est prêt à payer et combien vaut votre communauté.",
    tr_s3_t: "Concevez récompenses & accès VIP", tr_s3_d: "Configurez paliers, avantages, badges et conditions visuellement.",
    tr_s4_t: "Lancez votre Fan Pass", tr_s4_d: "Déployez un programme de fidélité tokenisé — rareté et statut intégrés.",
    tr_s5_t: "Suivez & développez", tr_s5_d: "Pilotez engagement, rétention et revenus depuis un seul dashboard.",

    tk_eyebrow: "Infrastructure invisible",
    tk_title: "La tokenisation, sans la complexité de la crypto.",
    tk_lede: "Vos fans ne voient jamais de wallet, de courbe ou de coin. Ils voient des passes, des badges et des accès. La couche token alimente discrètement propriété, rareté, portabilité et statut en arrière-plan.",
    tk_fans: "Ce que reçoivent vos fans", tk_you: "Ce qui l'alimente",
    tk_f1: "Fan Pass", tk_f2: "Badge VIP", tk_f3: "Points de récompense", tk_f4: "Drops privés",
    tk_f5: "Accès événements", tk_f6: "Contenu exclusif", tk_f7: "Statut communautaire", tk_f8: "Airdrops superfans",
    tk_p1: "Propriété", tk_p2: "Rareté", tk_p3: "Portabilité", tk_p4: "Transparence",
    tk_disclaimer: "AURA simule actuellement une future couche de fidélité tokenisée. Elle n'est pas connectée à une blockchain réelle et les tokens ne sont pas des investissements.",

    db_eyebrow: "Le produit",
    db_title: "Conçu pour les créateurs qui veulent agir, pas des vanity metrics.",
    db_lede: "Chaque chiffre mène à une décision : qui récompenser, quoi lancer, et combien ça peut rapporter.",
    db_k1: "Superfan Score", db_k2: "Maturité token", db_k3: "Revenu mensuel est.",
    db_k4: "Détenteurs de pass actifs", db_k5: "Récompenses réclamées", db_k6: "Croissance communauté",
    db_mod_rev: "Scénarios de revenus", db_mod_funnel: "Tunnel superfan",
    db_open: "Ouvrir le dashboard live",
    db_funnel_1: "Followers", db_funnel_2: "Engagés", db_funnel_3: "Superfans", db_funnel_4: "Détenteurs",

    uc_eyebrow: "Possibilités", uc_title: "Que peuvent lancer les créateurs ?",
    uc_lede: "Une audience. Une dizaine de façons de transformer la fidélité en relation qui vaut la peine d'être payée.",
    uc_1: "Fan club VIP", uc_2: "Communauté privée payante", uc_3: "Accès merch anticipé",
    uc_4: "Accès backstage", uc_5: "Contenu exclusif", uc_6: "Liste événements prioritaire",
    uc_7: "Collectibles numériques", uc_8: "Défis fans", uc_9: "Campagnes de récompenses",
    uc_10: "Drops token-gated", uc_11: "Points de fidélité", uc_12: "Classement superfans",

    pf_eyebrow: "Les chiffres · Exemples",
    pf_title: "Vos 100 prochains superfans valent plus que 100 000 followers.",
    pf_lede: "Scénarios illustratifs — pas des résultats clients. Les chiffres affichés sont des simulations de ce qu'une communauté activée peut générer.",
    pf_sim_tag: "Simulation",
    pf_c1_l: "100 superfans", pf_c1_v: "900 $", pf_c1_d: "/mois à 9 $/mois d'abonnement",
    pf_c2_l: "500 fan passes", pf_c2_v: "9 500 $", pf_c2_d: "revenu de lancement à 19 $ pièce",
    pf_c3_l: "Top 4 % activé", pf_c3_v: "12×", pf_c3_d: "revenu par fan vs. sponsorings",
    pf_quote: "« J'avais 140 K followers sans savoir que 4 000 d'entre eux paieraient volontiers pour être dans la pièce. AURA m'a montré que la pièce existait déjà. »",
    pf_quote_by: "Profil créateur fictif · illustratif",

    pr_eyebrow: "Tarifs", pr_title: "Commencez gratuitement. Activez quand vous êtes prêt.",
    pr_lede: "L'audit est toujours gratuit. Payez seulement au lancement.",
    pr_monthly: "Mensuel", pr_yearly: "Annuel · -20 %", pr_per: "/mois",
    pr_free_n: "Audit gratuit", pr_free_p: "0 $", pr_free_d: "Révélez votre potentiel.",
    pr_launch_n: "Launch", pr_launch_p: "29 $", pr_launch_d: "Un plan complet pour vous lancer.",
    pr_pro_n: "Creator Pro", pr_pro_p: "79 $", pr_pro_d: "Le moteur de monétisation complet.",
    pr_agency_n: "Agence / Label", pr_agency_p: "Sur devis", pr_agency_d: "Plusieurs créateurs, un cockpit.",
    pr_popular: "Le plus choisi",
    pr_cta_free: "Lancer l'audit gratuit", pr_cta_paid: "Choisir l'offre", pr_cta_agency: "Nous contacter",
    pr_fee_note: "Des frais de transaction peuvent s'appliquer sur les ventes de fan pass, les récompenses tokenisées ou les lancements de communauté payante.",
    pr_f_free: "Analyse Instagram|Superfan Score|Taux d'engagement|Aperçu maturité token|Scénario de revenu basique|3 recommandations",
    pr_f_launch: "Tout dans Gratuit|Diagnostic complet de communauté|Scénarios de revenus|Stratégie Fan Pass|Idées de paliers VIP & récompenses|Script de lancement|Checklist de campagne",
    pr_f_pro: "Tout dans Launch|Dashboard créateur|Builder de programme de fidélité|Configuration fan pass|Simulation d'airdrop|Analytics de campagne|Assets de lancement exportables",
    pr_f_agency: "Tout dans Pro|Plusieurs créateurs|Dashboard portfolio|Scoring des créateurs|Gestion de campagnes|Reporting de revenus",

    fcta_title: "Vos 100 prochains superfans vous suivent déjà.",
    fcta_sub: "Lancez un audit gratuit et rencontrez la communauté que vous ne saviez pas posséder.",
    fcta_btn: "Les trouver maintenant",

    ft_tag: "Révéler. Connecter. Récompenser.",
    ft_product: "Produit", ft_company: "Entreprise", ft_legal: "Légal",
    ft_disclaimer: "AURA est une plateforme de monétisation pour créateurs. La couche de fidélité tokenisée est actuellement une simulation d'une infrastructure future et ne constitue ni un conseil financier ni un produit d'investissement.",
    ft_rights: "© 2026 AURA. Tous droits réservés."
  }
});
